### ISSUE TITLE
Named vs. numbered lessons

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#342]
What should we use.

**Comment by brymz** [comment]
Given the cumbersome logistics of the choice to combine weeks, I think it's hard to justify keeping the numbered system. Now that I'll have the time to get the work done, I think it makes a lot of sense to do.

**Comment by ethanwhite** [comment]
Sounds good. Let's go for it.

**Comment by brymz** [comment]
Be sure to:
- [ ] Combine weeks for R lectures 1-3
- [ ] Collapse weeks following combine

**Comment by brymz** [comment]
Restructure is going smoothly. I've updated the page build and am just updating the content pages.

Do we want to update all of the file names away from 'numbered' (r-1.md -> r-intro.md)? This shouldn't affect the page builds, but would likely shuffle the files out of order in the directory. Also, updating all of the names with the restructure might make the restructure commits difficult to see. So, if yes to the first question, do I wait to rename the files until after the restructure is merged? [This is how I will proceed with a PR, unless I hear otherwise.]

**Comment by ethanwhite** [comment]
> Do we want to update all of the file names away from 'numbered' (r-1.md -> r-intro.md)? This shouldn't affect the page builds, but would likely shuffle the files out of order in the directory.

Yes.

> Also, updating all of the names with the restructure might make the restructure commits difficult to see. So, if yes to the first question, do I wait to rename the files until after the restructure is merged? [This is how I will proceed with a PR, unless I hear otherwise.]

Whatever is easiest is for you.
