### ISSUE TITLE
Move relevant pieces of Python and R lecture material into main Data Carpentry repositories

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#4]

**Comment by brymz** [comment]
When this issue was opened, I think we were still in `weecology/datacap-semester-biology`. So, have we moved *all* of the materials into the "main Data Carpentry repo"? Based on what I know about the Data Carpentry repo organization, most of the teaching materials are being maintained within their lesson (i.e., there is no "main repo" for teaching materials). Have we adequately addressed this issue to close it?
