### ISSUE TITLE
"Fork our course" blog post

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#414]
Write a blog post advertising what we've done.

**Comment by brymz** [comment]
I've started a draft for the blog on the wiki: https://github.com/datacarpentry/semester-biology/wiki/Data-Carpentry-for-Biologists:--Introductory-data-science-resources-and-course-website

**Comment by brymz** [comment]
The draft blog post is complete and ready for review. Though, I do have some concerns:

- Some of the information/links are a bit redundant. In some ways that is ok because I have introduced each of the important links to our site in various contexts/language. But, maybe it also means that the post could be organized more concisely.
- Right now the post lacks a 'hook'. The post is written in a way that implies the reader is already interested in the project and wants to know more. I haven't come up with a good way/statement that could get anyone interested. Maybe the title is the best place for attention grabbing.
- There are no pictures. I considered screenshots, but thought the links largely served to direct attention to the site. I also didn't want the post to get very long with pictures. So instead of including all of the possibilities, I left pictures out. I think we should aim for at least an image or two to catch the eye of the reader.

**Comment by brymz** [comment]
https://jabberwocky.weecology.org/2016/11/14/fork-our-course-a-semester-long-data-carpentry-course-for-biologists/
