### ISSUE TITLE
Convert slide decks to html slides

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#501]
There aren't a lot of slide decks in this course, but there are a few and it would be easier to use them if they were html slide decks where the instructor could just click on a link and show the slides.

**Comment by brymz** [comment]
Do you have a recommendation for "the best" way to go about making this conversion?

**Comment by ethanwhite** [comment]
Sadly no.

**Comment by brymz** [comment]
https://github.com/tasmo/reveal-jekyll or https://github.com/ramnathv/slidify

**Comment by cboettig** [comment]
Consider having the slide decks rendered from *.Rmd notebook or Jupyter notebook files directly?  (Slidify does this, `slidy` and `ioslides` are already built into RStudio's Rmd templates for presentations (better than the much older R Presentation format that's still in the RStudio menu).  You might take a look at [rmdshower](https://github.com/mangothecat/rmdshower) as a newer format.  Of course something similar can be done with Jupyter's built-in rendering to HTML5 slides.

Since these are just output formats, this makes it possible to render slides, exercises, and lecture notes / reading material from the same source (though not sure how practical that is; worked ok for me in my last python-based class, still mulling it over).

**Comment by ethanwhite** [comment]
> Consider having the slide decks rendered from *.Rmd notebook or Jupyter notebook files directly?

We've talked about this. In an ideal world we'd be able to avoid an external rendering step and have it handled entirely by the base GitHub pages Jekyll install. That would allow users not familiar with Rmd/Jupyter to change the markdown and have it automatically render on their course website. If we can'tv get that to work then I think using Rmd/Jupyter is a good solution.

**Comment by cboettig** [comment]
Yup, of course with only GitHub rendering you're either left rendering the code externally anyway or just pasting in code that isn't actually executed.  

I'm prepping materials for my course this Spring and adapting (or hoping to adapt) liberally from your excellent work!  I've made a mock-up of this approach where notes are written in .Rmd instead of .md, and they are knit & rendered by jekyll automatically on push via Continuous Integration (circle-ci), since obviously github rendering won't run the R code.  Here's the current skeleton: https://github.com/ds421/rcds

**Comment by brymz** [comment]
Thanks for the feedback, @cboettig. We would be excited to include your course in our 'customized courses' list when you get it up and running.

Do you think that you will be using slides primarily throughout your course? We use .md primarily to guide @ethanwhite's live-coding. They are more 'lecture notes' than visual aid. I would be curious about your thoughts in adding CI to the prereq knowledge for instructors (perhaps without a deep programming background) to get started customizing the course. We have avoided a `makefile` or other build structures to keep the site development simple.

**Comment by cboettig** [comment]
Hey Zack,

Thanks; this will be my first time through this particular course so still figuring it out; but no, I don't expect slides to play a major part.  I have a 2hr session once a week, plus 1 hr lab; I'll probably talk + some live code for the first 20-30 minutes and then switch over into students working through exercises in pairs; leaving me to float around and address specific issues either to individuals or the class at large.

Re keeping setup simple, I agree entirely.  It's worth noting that the CI part in my setup is entirely optional though -- the site (the website dir, https://github.com/ds421/rcds/tree/master/website) is 100% GitHub-pages compatible.  The CI system automates knitting *.Rmd files to make the *.md ones, but one could just as well do that locally (by script) or just by hand (i.e. knitting each one manually in RStudio).  Jekyll ignores the .Rmd files and just reads the .md files all the same anyhow.  

Admittedly this may still be a confusing level of complication, but fun to experiment.

**Comment by brymz** [comment]
Files to convert to Rmd/Rpres (I think we will go with a manual knit for now):
- [ ] materials/basic-debugging.pdf
- [ ] materials/databases-structure.pdf
- [ ] materials/intro-to-databases.pdf
- [ ] materials/lists-loops-methods-nesting.pdf
- [ ] materials/R-and-python.pdf

**Comment by brymz** [comment]
I have reviewed the list of PDF presentation files that remain in the course and I have found that the files:

* have already been replaced and updated with MD in our set of 'lecture notes' 
    * materials/basic-debugging.pdf
    * materials/databases-structure.pdf
    * materials/intro-to-databases.pdf
* or are no longer relevant to the SQL/R-centric form of the course
    * materials/lists-loops-methods-nesting.pdf
    * materials/R-and-python.pdf

I recommend that we `rm` the replaced/outdated files and leave the python-related files as is. Instructors that prefer to use HTML slides over MD pages should be able to modify the current files' format to Rmd and generate presentation output.

**Comment by ethanwhite** [comment]
> I recommend that we rm the replaced/outdated files and leave the python-related files as is. Instructors that prefer to use HTML slides over MD pages should be able to modify the current files' format to Rmd and generate presentation output.

👍
