### ISSUE TITLE
Improve phrasing of Sql-practice-basic-queries-review-R & add output solutions

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#534]
1.1 and 1.2 are intended to have `species_id` in the solutions. This isn't clear from the phrasing and the problems are missing output solutions.

**Comment by brymz** [comment]
Was this review helpful / important again this year? 

We put this here last year from student feedback to @andrewmarx.  Was there similar feedback this year? If we were to keep this in defensively, is this the best place?

**Comment by ethanwhite** [comment]
I think a little refresher on this stuff is generally useful, but I'm happy to go with whatever @andrewmarx things is best here.

**Comment by andrewmarx** [comment]
I had a couple different goals with this originally. The first was to just keep people practicing SQL. I think the order of things was different last year where there was a larger gap between this and the previous assignment involving SQL.

The other was to have people interpret the problem without output to guide them, and to only have them specifically give me what I ask for. In 1 and 2, I specifically ask for them to give me a list of individuals. The other parts just dictate how that list should be ordered, but shouldn't be included because I didn't request that information. It's useful to have it visible while developing a query for troubleshooting, but not for the final result.

That was the intention, anyway, but I think my attempt at making that clear without giving away the answer could be confusing/making them over think the problem. I don't want to explicitly tell them to exclude those extra columns, but to have them think carefully about whether or not I actually asked for them.

**Comment by brymz** [comment]
@andrewmarx, I can see where you are coming from but I agree with @ethanwhite that something has to be changed with this exercise to help the students. I think the language can be revised to more clearly define the output expected of the students and/or we can add output to be sure. Alternately, we can revise the problem to get more clearly at your two goals of practicing SQL AND encouraging the students to consider the 'necessary' information.
 
The exercise asks students to "think carefully about which fields are actually relevant to the problem", but the problem makes an assumption about the identity of an individual that leaves the expected output unclear. An adequate solution to the first problem could identify males in the list by their `record_id`, `species_id`, or `weight`.  Based on what I think is the desired outcome, we would have to mention that we expect the individuals to be identified by  `species_id`. To leave some room for problem solving on the part of the student, we might consider revising the problems as scientific questions or hypotheses. That way each problem has a clear "relevance" that can be evaluated by the students.

**Comment by brymz** [comment]
Are you going to get back to this @andrewmarx? or is this on me?

**Comment by andrewmarx** [comment]
I'll think about it and try to modify things so that there is less ambiguity and the overall goal is more clear.

**Comment by brymz** [comment]
Did you make any progress on this @andrewmarx? Or, can you give me some direction for revisions?

I would lean towards rephrasing the problems as scientific questions or hypotheses and include output solutions. The student would be left to generate the relevant query without direct instruction as to the commands to use.
