### ISSUE TITLE
Add more very basic for loops exercises to assignment

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#552]
Some students are still struggling with the concept and adding more basic ones to make sure the fundamentals are solid before moving on would be helpful.

**Comment by brymz** [comment]
Are there particular hang-ups to address?

**Comment by ethanwhite** [comment]
@andrewmarx should be able to clarify.

**Comment by andrewmarx** [comment]
I wouldn't say there are any particular hangups; just a need for more practice with basic concepts to build confidence before incorporating for loops with problem solving. For example, "Print the numbers 3 to 10 with a for loop" and "Print the values in vector x using an index in a for loop." I sent a file to the class with a bunch of examples that could just be converted to actual questions. I'll try to do that sometime over the next week.

**Comment by brymz** [comment]
After all of our recent discussion about collaborative development, I wonder if this is a chance to use/find basic exercises elsewhere as a supplemental 'pre-assignment'

Otherwise, I am thinking of adding two problems: 1) a loop over an index `for(i in 1:10)` and 2) a loop over a vector `for (seq in sequences)`. The problems would use a missing pieces or modify the code style for a slow introduction to the code syntax.

**Comment by ethanwhite** [comment]
I don't mind bringing in something external, but it would have to be licensed for reuse. I would like these to be part of the formal assignment given the degree of confusion. Your suggested additions sound fine to me.

**Comment by brymz** [comment]
Didn't find much that I thought could be useful from a quick keyword search. I'll get started on the exercise additions.
