### ISSUE TITLE
Determine Data Carpentry name use permission/restrictions for forked repos

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#588]
As per discussion with @palderman in #578, @ethanwhite has contacted Data Carpentry board and will respond with decision.

**Comment by ethanwhite** [comment]
Just a quick update that I've put this in front of the Data Carpentry Board and am waiting on feedback from a few more folks before we figure out how this will work initially. I've pinged them again in the hopes of getting @palderman an answer shortly.

**Comment by ethanwhite** [comment]
Sorry for the delay @palderman. The short answer is that on a trial basis (to help us explore how this will work in the long-term) I'm in charge of green lighting use of the Data Carpentry name for courses building on this material. In general I'm positively predisposed to this, but we should talk either via email or video chat about exactly what you're planning so that we make sure that it fits in with DC's general efforts & approach to things before we officially give you the go ahead on using the name. Send me an email when you're ready to chat and we'll go from there.

@brymz - we should add a note to the docs letting people know that if they are interested in using the "Data Carpentry" name that they should contact me.
