### ISSUE TITLE
Rework git materials

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/semester-biology#591]
The current design of the git materials is to do one example in class and a separate example with parallel steps for the exercises. This has ended up causing quite a bit of confusion both times I've taught it because students don't manage to keep two separate repositories going for the two separate projects. This was even true this year after very clear warnings about the need to do so.

Options for addressing this:

1. Try to stop the students from following along with the lecture on their computers. This is different from what they've done all semester and some won't listen.
2. Make an integrated lecture/exercise where they need to do the work done during the lecture and then do another round of equivalent work themselves. The downside here is that broken installs will be more disruptive.

I'm currently leaning towards option 2. Thoughts @brymz?

**Comment by brymz** [comment]
I also lean to option 2, but perhaps with less ambition. As an entirely new programming language/platform, just being able to follow along with the lecture might be a sufficient expectation for the assignment. A few exercises in between class periods or at the end that take a bit more figuring out would fit the "another round of equivalent work".

Alternately, if the Git lesson was moved to the beginning of the course, there may be no need for detailed practice other than the practical application of submitting assignments throughout the course. I checked out @jennybc's http://happygitwithr.com/ resources, which struck me as a bit advanced for our 'novice' students. But, I thought her approach was interesting. It seems she expects students to do some pre-class preparation ("summer reading") to setup Git and get familiar with it so that they are ready to use it in class (or have at least seen it before).

**Comment by jennybc** [comment]
Hi! One day 1 of class, I ask everyone to attempt Git installation and setup for day 2. This usually gives them a full weekend, due to how our semester starts. The vast majority succeed but of course some are unlucky and do not. I have lots to TAs on hand for day 2, in class and right after re: office hours. We do get everyone set up within 1st week, I'd say.

I create a repo for each student within the course organization. In class we "take possession' of it, all working in sync. First homework is to edit the README. Hopefully locally, then push. But plan B is to edit in browser and come to office hours for extra help. Every subsequent homework requires pushing files (practice!), opening an issue (practice!) and visiting the repo of two peers (practice!), navigating their repo (practice!), and leaving comments in an issue (practice!). Every week for 13 weeks.

I've been surprised at how little we talk about Git and GitHub, actually. I thought it would be much worse.

Now, my course is entirely R based, so I think the Git client offered by RStudio is a HUGE help to us. I bet my students do almost 100% of their Git work through that. I don't know if that would apply in your case?

**Comment by brymz** [comment]
Thanks for the feedback, @jennybc.

@ethanwhite, let me know if you've reached some clarity on how you would like to proceed.

**Comment by brymz** [comment]
Based on discussion with @ethanwhite...

- [ ] move lesson to wk 6 (behind data vis)
- [ ] revise the lecture and assignment to start with creating remote repo from class organization
- [ ] revise the lecture to parallel assignment with houseelf data
- [ ] add projects introduction as a reading (?)
- [ ] add task to set-up repo for project and commit/push a paragraph for project proposal

**Comment by ethanwhite** [comment]
Thanks for the great feedback @jennybc. We didn't quite have the nerve to do this on day one, but we've moved it up substantially and plan to require it for course projects in large part thanks to your feedback. We'll see how it goes next year and if it goes well that will maybe give me the confidence to go full Jenny (we've already got "jennying a repository", so I figure we might as well also have 'go full Jenny' for teaching git right from the beginning 😀.

**Comment by ethanwhite** [comment]
Plan looks great @brymz!

**Comment by jennybc** [comment]
@ethanwhite Glad to hear it was helpful! I think my bottom line is to explicitly "teach Git" as little as possible and, instead, to just have them use it on a near-daily basis to do something useful = take your course.

Next time I upgrade my Git teaching stuff, I am totally taking inspiration from this amazing slide deck:

https://speakerdeck.com/alicebartlett/git-for-humans

**Comment by ethanwhite** [comment]
Ooh, that is a really nice slide deck!

**Comment by jennybc** [comment]
I have written this elsewhere in words, but I really like her illustration of it:

When you're using Git, a "commit" is a version of the world that -- in Word or Excel -- would have caused you to rename the file w/ initials and/or date. 💡💡💡
