### ISSUE TITLE
Redesigning Programming Fundamentals section

### ISSUE THREAD

**Issue by andrewmarx** [datacarpentry/semester-biology#819]
Last semester we had issues with the Programming Fundamentals section being too overwhelming for students, and in general this section has always been challenging because of its more abstract nature. Here are some thoughts on a potential restructuring:

- Too much, too fast: Conditionals and functions should probably be in separate weeks. This will avoid overload, and also allow for more practice time with each.
- Order: I definitely think loops should be kept until last. They might be the most difficult topic of the three to learn. The order of conditionals and functions is less important, and there are justifications for having either first. I think conditionals are a little easier to learn, so would pair well with learning other things like style at the same time, and style should be early
- Lack of experience: One of the biggest issues with loops that I observed was less about loops and more about a lack of practice using indexes to access vectors and dataframes. I find many people have trouble using [ ] to access these data structures, in part because we are so dependent on dplyr, which hides it away from them and they never get comfortable with it.
- Enforce basic style rules: admittedly, poor style does make grading harder for me, but it also makes it more difficult for students to understand their own code. Additionally, getting people in the habit of using good style is just a good idea for down the road when they have to collaborate with people, submit code as SI for articles, etc.
- Embrace braces {}: I think the very first thing we should do is discuss the idea of braces as a way to "group" lines of code. This starts the idea of grouping related lines of code. This can include two examples: one via script where setting the cursor to a line with a brace and running it runs the entire block of code. The other would be via terminal, where a series of commands won't run until the closing brace is entered.
- Examples: I know there is a desire to apply these concepts to ecological/scientific applications, but in general students already sometimes struggle deciphering the scientific content in exercises. In the programming fundamentals section, it is only even more challenging. I would encourage more non-scientific exercises before going into the scientific ones. For example, just have them recreate simple math functions, like add() and abs(). With loops, just have them search for particular letters in a vector of characters, then finding words in a vector, then searching for words in a matrix. A full word search was my homework assignments in highschool right after learning loops, conditionals, and functions. A wordsearch is basically the same as the exercise looping over cells in a raster we had last semester, but the context and data structures are simpler.

With that, here is an example schedule:

Week 1
  - Day 1: 
    - braces
    - style (just indenting)
    - basic if statements
  - Day 2: 
    - style (more broadly, like variable names, whitespace, etc. I would personally prefer requiring them to enable "Global Options" -> "Code" -> "Diagnostics" -> "Provide R style diagnostics")
    - Nested if statements
    - Anything else we might think of with if statements. Especially including practical examples where it is useful, like checking for a results file prior to rerunning a long analysis.

Week 2
  - Day 1
    - functions
    - emphasize importance of parameters, and not using global variables
    - require explicit returns, even though they aren't technically required
  - Day 2
    - function testing
    - maybe using stop() with conditionals internally in functions to stop an analysis where something has gone wrong

Week 3
  - Day 1
    - Don't be afraid to *briefly* illustrate the concept of loops with while(). It's simpler/less abstract than for loops. I've had a couple people really struggle with the concept of loops, and illustrating loops to them with while loops really helped them.
    - for loops: I would do indexing first, then iterators. Indexing is a little less abstract, and gives more insight into how loops works.
  - Day 2
    - apply() functions: part of the reason people struggle with these is that they just aren't comfortable with functions. Hopefully a full week/assignment dedicated to just functions will make this easier.

**Comment by ethanwhite** [comment]
Thanks @andrewmarx! I definitely agree that we need the extra week to cover fundamentals and think there are a ton of good ideas here. I'll be doing planning for the semester next week and will be back in touch as I integrate these ideas and think about how to give us more time to cover that material.

**Comment by ethanwhite** [comment]
Thanks again for this @andrewmarx! I think your breakdown of the problems and challenges is excellent and I think we definitely need to stretch out the material more. I totally agree that starting with super simple examples and exercises before trying to work with more realistic problems is the way to go, and we definitely need more time to do that.

As you've noted iteration is the biggest challenge and so I think we really need 2 weeks to cover it. Therefore, what I'm currently planning on is using the current `Putting it all together` week as a fourth week for fundamentals to give us:

1. Functions
2. Conditionals
3. Iteration: vectorization + apply/map
4. Loops

We then integrate some of the material from `Putting it all together` into the first couple of weeks of this fundamentals section (including your suggestions about style) and also into the `Computational Projects` week (which needs to be renamed) earlier in the semester. We integrate the "combining ideas" component using 1 exercise/week at the end of the assignment (possibly optional) that gets folks grappling with more complex combinations of the ideas they've learned up to that point.

I agree that the order on functions & conditionals is approximately a toss up. The reason I've tended to teach functions first is that I find it hard to come up with a lot of good examples of linear conditional code that is vaguely realistic. Since the existing exercises are also stacked this way I'm hesitant to reorder this unless we feel strongly that it's important for student learning and it doesn't feel like either of us is there (though I'm certainly open to additional discussion).

**Comment by ethanwhite** [comment]
OK, I think I've moved all of the key ideas into the issues linked above. If I'm still missing something important please let me know.

**Comment by ethanwhite** [comment]
Closing since this has all been split out into the smaller issues above. Thanks again @andrewmarx!
